apiVersion: v1
kind: ConfigMap
metadata:
  name: massage-app-config
  namespace: massage-booking
data:
  FLASK_ENV: "production"
  DB_HOST: "massage-db"
  DB_NAME: "massage_db"
  DB_USER: "postgres"

---
apiVersion: v1
kind: Secret
metadata:
  name: massage-app-secret
  namespace: massage-booking
type: Opaque
stringData:
  DB_PASSWORD: "postgres"

---
apiVersion: v1
kind: Secret
metadata:
  name: massage-db-secret
  namespace: massage-booking
type: Opaque
stringData:
  POSTGRES_PASSWORD: "postgres"
