apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: massage-app-ingress
  namespace: massage-booking
spec:
  rules:
    - host: massage.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: massage-app-service
                port:
                  number: 80
